/*!
 * Dominion Set Generator Data
 * Copyright 2012, Wei-Hwa Huang
 * Licensed for use by Funsockets, Inc.
 *
 * Last update: Fri Jun 14 15:11:47 2013
 */

var DominionSetGeneratorData = {
  cardData: {
    'Alchemist' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Speeder' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Apothecary' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Scouter' : 4,
      'Topdecker' : 1,
      'Speeder' : 3,
      'Variance' : 1,
      'Chooser' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Apprentice' : {
      'Alchemy' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Selftrasher' : 1,
      'Speeder' : 2,
      'Variance' : 2,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Familiar' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Attack' : 1,
      'Giver' : 1,
      'Speeder' : 1,
      'Interactive' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Golem' : {
      'Alchemy' : 1,
      'Expensive' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Selfmiller' : 4,
      'Speeder' : 5,
      'Variance' : 2,
      'Chooser' : 1,
      'Brancher' : 1
    },
    'Herbalist' : {
      'Alchemy' : 1,
      'Cost2' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 1,
      'Topdecker' : 1,
      'Variance' : 3,
      'Chooser' : 1,
      'Deckchanger' : 1
    },
    'Philosopher\'s Stone' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Improver' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Possession' : {
      'Alchemy' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Helper' : 1,
      'Miller' : 5,
      'Variance' : 4,
      'Chooser' : 1,
      'Interactive' : 1
    },
    'Scrying Pool' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Miller' : 1,
      'Spier' : 1,
      'Speeder' : 3,
      'Variance' : 2,
      'Chooser' : 3,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Transmute' : {
      'Alchemy' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'University' : {
      'Alchemy' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Gainer' : 1,
      'Chooser' : 3,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Vineyard' : {
      'Alchemy' : 1,
      'Cheap' : 1,
      'Victory' : 2,
      'Antisplitter' : 1,
      'Interactive' : 1
    },
    'Black Market' : {
      'Promo' : 1,
      'BlackMarket' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Variance' : 4,
      'Chooser' : 2
    },
    'Envoy' : {
      'Promo' : 1,
      'Envoy' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 4,
      'Helper' : 1,
      'Selfmiller' : 5,
      'Speeder' : 4,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 1
    },
    'Stash' : {
      'Promo' : 1,
      'Stash' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Variance' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Walled Village' : {
      'Promo' : 1,
      'WalledVillage' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Governor' : {
      'Promo' : 1,
      'Governor' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Carddrawer' : 2,
      'Mutator' : 1,
      'Helper' : 1,
      'Speeder' : 2,
      'Chooser' : 3,
      'Interactive' : 1,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Adventurer' : {
      'Base' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Selfmiller' : 2,
      'Speeder' : 3,
      'Variance' : 1
    },
    'Bureaucrat' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Gainer' : 1,
      'Attack' : 1,
      'Shrinker' : 1,
      'Speeder' : -1,
      'Slower' : 1,
      'Variance' : 2,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Cellar' : {
      'Base' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Antisplitter' : 1,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Chancellor' : {
      'Base' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 2,
      'Selfmiller' : 8,
      'Speeder' : 6,
      'Variance' : 2,
      'Chooser' : 2
    },
    'Chapel' : {
      'Base' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Selftrasher' : 3,
      'Variance' : 1,
      'Chooser' : 2,
      'Deckchanger' : 3
    },
    'Council Room' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Carddrawer' : 4,
      'Helper' : 1,
      'Selfmiller' : 4,
      'Speeder' : 4,
      'Variance' : 1,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Feast' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Mutator' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Festival' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Buyer' : 1,
      'Coinage' : 2,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Gardens' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Victory' : 3,
      'Antisplitter' : 1,
      'Improver' : 1,
      'Interactive' : 1
    },
    'Laboratory' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Speeder' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Library' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 3,
      'Grower' : 1,
      'Selfmiller' : 3,
      'Speeder' : 4,
      'Variance' : 1,
      'Chooser' : 1
    },
    'Market' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Militia' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 2,
      'Attack' : 1,
      'Shrinker' : 2,
      'Variance' : 2,
      'Interactive' : 2
    },
    'Mine' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 1,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Antiterminus' : 1
    },
    'Moat' : {
      'Base' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Blocker' : 2,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Interactive' : 1
    },
    'Moneylender' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 3,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Variance' : 2,
      'Deckchanger' : 1
    },
    'Remodel' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Mutator' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Smithy' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Selfmiller' : 3,
      'Speeder' : 3,
      'Variance' : 1
    },
    'Spy' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Attack' : 1,
      'Miller' : 1,
      'Spier' : 1,
      'Speeder' : 2,
      'Chooser' : 1,
      'Interactive' : 2,
      'Antiterminus' : 1
    },
    'Thief' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Attack' : 1,
      'Trasher' : 1,
      'Miller' : 2,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Throne Room' : {
      'Base' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Multiplier' : 1,
      'Cumulative' : 2,
      'Variance' : 3,
      'Brancher' : 1
    },
    'Village' : {
      'Base' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Witch' : {
      'Base' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Attack' : 1,
      'Giver' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 1,
      'Interactive' : 2
    },
    'Woodcutter' : {
      'Base' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Coinage' : 2,
      'Deckchanger' : 1
    },
    'Workshop' : {
      'Base' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Chooser' : 2,
      'Deckchanger' : 1
    },
    'Baron' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Buyer' : 1,
      'Gainer' : 1,
      'Coinage' : 4,
      'Carddrawer' : -1,
      'Variance' : 3,
      'Chooser' : 1,
      'Deckchanger' : 2
    },
    'Bridge' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 2,
      'Buyer' : 1,
      'Coinage' : 2,
      'Deckchanger' : 1
    },
    'Conspirator' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Antiterminus' : 1
    },
    'Coppersmith' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Variance' : 3
    },
    'Courtyard' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Scouter' : 1,
      'Topdecker' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 1
    },
    'Duke' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Victory' : 3,
      'Antisplitter' : 1,
      'Interactive' : 1
    },
    'Great Hall' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Victory' : 1,
      'Multicolor' : 1,
      'Chainer' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Interactive' : 1,
      'Antiterminus' : 1
    },
    'Harem' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Victory' : 1,
      'Treasure' : 1,
      'Multicolor' : 1,
      'Cumulative' : 1,
      'Interactive' : 1,
      'Antiterminus' : 1
    },
    'Ironworks' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Masquerade' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Selftrasher' : 1,
      'Trasher' : 1,
      'Helper' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Mining Village' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Antisplitter' : 1,
      'Coinage' : 2,
      'Carddrawer' : 1,
      'Selftrasher' : 1,
      'Speeder' : 1,
      'Deckchanger' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Minion' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 2,
      'Coinage' : 2,
      'Attack' : 1,
      'Shrinker' : 1,
      'Grower' : 1,
      'Selfmiller' : 2,
      'Miller' : 1,
      'Speeder' : 4,
      'Variance' : 2,
      'Chooser' : 3,
      'Interactive' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Nobles' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Victory' : 2,
      'Multicolor' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 3,
      'Selfmiller' : 3,
      'Speeder' : 3,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Pawn' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Saboteur' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Attack' : 1,
      'Trasher' : 1,
      'Variance' : 3,
      'Interactive' : 2
    },
    'Scout' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : 1,
      'Scouter' : 4,
      'Topdecker' : 2,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Antiterminus' : 1
    },
    'Secret Chamber' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Coinage' : 2,
      'Discardcasher' : 1,
      'Blocker' : 1,
      'Topdecker' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Interactive' : 1,
      'Antiterminus' : 1
    },
    'Shanty Town' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Grower' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Steward' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Carddrawer' : 2,
      'Selftrasher' : 2,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 2
    },
    'Swindler' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Attack' : 1,
      'Trasher' : 1,
      'Miller' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Interactive' : 2
    },
    'Torturer' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 2,
      'Carddrawer' : 3,
      'Attack' : 1,
      'Giver' : 1,
      'Shrinker' : 2,
      'Selfmiller' : 3,
      'Speeder' : 3,
      'Variance' : 1,
      'Interactive' : 2
    },
    'Trading Post' : {
      'Intrigue' : 1,
      'Intrigue2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : -1,
      'Variance' : 2,
      'Chooser' : 1
    },
    'Tribute' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Splitter' : 0.5,
      'Terminus' : 0.5,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Coinage' : 3,
      'Carddrawer' : 1,
      'Helper' : 1,
      'Selfmiller' : 2,
      'Miller' : 2,
      'Speeder' : 2,
      'Interactive' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Upgrade' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Mutator' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Wishing Well' : {
      'Intrigue' : 1,
      'Intrigue1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Antiterminus' : 1
    },
    'Bank' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost7' : 1,
      'Expensive' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Variance' : 2,
      'Antiterminus' : 1
    },
    'Bishop' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chipper' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 1,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Helper' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'City' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Medichainer' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Contraband' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Variance' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Counting House' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Coinage' : 3,
      'Variance' : 4
    },
    'Expand' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost7' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Forge' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost7' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : -2,
      'Selftrasher' : 2,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Deckchanger' : 2,
      'Antiterminus' : 1
    },
    'Goons' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Chipper' : 1,
      'Cumulative' : 1.5,
      'Buyer' : 1,
      'Coinage' : 2,
      'Attack' : 1,
      'Shrinker' : 2,
      'Variance' : 1,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Grand Market' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 2,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Hoard' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Variance' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'King\'s Court' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost7' : 1,
      'Expensive' : 1,
      'Multiplier' : 1,
      'Cumulative' : 2,
      'Variance' : 4,
      'Brancher' : 1
    },
    'Loan' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Selftrasher' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Mint' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Selftrasher' : 2,
      'Variance' : 1,
      'Chooser' : 1,
      'Deckchanger' : 3
    },
    'Monument' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chipper' : 1,
      'Cumulative' : 1,
      'Coinage' : 2
    },
    'Mountebank' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1.5,
      'Coinage' : 2,
      'Attack' : 1,
      'Giver' : 2,
      'Chooser' : 1,
      'Interactive' : 2
    },
    'Peddler' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Quarry' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Discounter' : 1,
      'Antiterminus' : 1
    },
    'Rabble' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Attack' : 1,
      'Miller' : 1,
      'Speeder' : 3,
      'Variance' : 1,
      'Chooser' : 1,
      'Interactive' : 2
    },
    'Royal Seal' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Antisplitter' : 1,
      'Topdecker' : 1,
      'Antiterminus' : 1
    },
    'Talisman' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Trade Route' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 1,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Chooser' : 2,
      'Deckchanger' : 1
    },
    'Vault' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Discardcasher' : 1,
      'Helper' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 2,
      'Interactive' : 1,
      'Antiterminus' : 1
    },
    'Venture' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Variance' : 1,
      'Antiterminus' : 1
    },
    'Watchtower' : {
      'Prosperity' : 1,
      'Prosperity2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : 2,
      'Blocker' : 1,
      'Grower' : 1,
      'Topdecker' : 1,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 3,
      'Interactive' : 1
    },
    'Worker\'s Village' : {
      'Prosperity' : 1,
      'Prosperity1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Buyer' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Deckchanger' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Ambassador' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : -1,
      'Selftrasher' : 2,
      'Attack' : 1,
      'Giver' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 2,
      'Deckchanger' : 2
    },
    'Bazaar' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Medichainer' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Caravan' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Duration' : 1,
      'Chainer' : 1,
      'Duration' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Speeder' : 2,
      'Antiterminus' : 1
    },
    'Cutpurse' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 2,
      'Attack' : 1,
      'Shrinker' : 1,
      'Variance' : 1,
      'Interactive' : 2
    },
    'Embargo' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Helper' : 1,
      'Interactive' : 1
    },
    'Explorer' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Carddrawer' : 1,
      'Variance' : 2,
      'Deckchanger' : 1
    },
    'Fishing Village' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Duration' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Duration' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Coinage' : 2,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Ghost Ship' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : 2,
      'Attack' : 1,
      'Shrinker' : 1,
      'Selfmiller' : 2,
      'Speeder' : 2,
      'Slower' : 1,
      'Variance' : 1,
      'Interactive' : 2
    },
    'Haven' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Duration' : 1,
      'Chainer' : 1,
      'Duration' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Chooser' : 3,
      'Antiterminus' : 1
    },
    'Island' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Victory' : 1,
      'Multicolor' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Variance' : 2,
      'Chooser' : 3,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Lighthouse' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Duration' : 1,
      'Chainer' : 1,
      'Duration' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Blocker' : 1,
      'Antiterminus' : 1
    },
    'Lookout' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Selftrasher' : 1,
      'Topdecker' : 1,
      'Selfmiller' : 1,
      'Speeder' : 2,
      'Variance' : 2,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Merchant Ship' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Duration' : 1,
      'Terminus' : 1,
      'Duration' : 1,
      'Cumulative' : 1,
      'Coinage' : 4
    },
    'Native Village' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Chooser' : 3,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Navigator' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Scouter' : 5,
      'Topdecker' : 5,
      'Selfmiller' : 5,
      'Speeder' : 5,
      'Variance' : 2,
      'Chooser' : 2
    },
    'Outpost' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Duration' : 1,
      'Terminus' : 1,
      'Duration' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 3,
      'Speeder' : 3,
      'Variance' : 2
    },
    'Pearl Diver' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : 1,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Antiterminus' : 1
    },
    'Pirate Ship' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1.5,
      'Coinage' : 2,
      'Attack' : 1,
      'Trasher' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Interactive' : 2
    },
    'Salvager' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 1
    },
    'Sea Hag' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Attack' : 1,
      'Giver' : 1,
      'Interactive' : 2
    },
    'Smugglers' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Helper' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Tactician' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Duration' : 1,
      'Splitter' : 1,
      'Terminus' : 1,
      'Duration' : 1,
      'Antisplitter' : 1,
      'Buyer' : 1,
      'Selfmiller' : 3,
      'Speeder' : 5,
      'Variance' : 1,
      'Deckchanger' : 1,
      'Brancher' : 1
    },
    'Treasure Map' : {
      'Seaside' : 1,
      'Seaside1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Carddrawer' : -1,
      'Variance' : 3,
      'Deckchanger' : 1
    },
    'Treasury' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Warehouse' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Speeder' : 3,
      'Variance' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Wharf' : {
      'Seaside' : 1,
      'Seaside2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Duration' : 1,
      'Cumulative' : 1,
      'Buyer' : 2,
      'Carddrawer' : 4,
      'Speeder' : 3,
      'Variance' : 1,
      'Deckchanger' : 2
    },
    'Fairgrounds' : {
      'Cornucopia' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Victory' : 3,
      'Antisplitter' : 1,
      'Variance' : 1,
      'Interactive' : 1
    },
    'Farming Village' : {
      'Cornucopia' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Fortune Teller' : {
      'Cornucopia' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Attack' : 1,
      'Miller' : 1,
      'Variance' : 2,
      'Interactive' : 2
    },
    'Hamlet' : {
      'Cornucopia' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Buyer' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Chooser' : 3,
      'Deckchanger' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Harvest' : {
      'Cornucopia' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 3,
      'Speeder' : 4,
      'Variance' : 2
    },
    'Horn of Plenty' : {
      'Cornucopia' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Antisplitter' : 1,
      'Chooser' : 3,
      'Antiterminus' : 1
    },
    'Horse Traders' : {
      'Cornucopia' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Coinage' : 2,
      'Carddrawer' : -2,
      'Blocker' : 1,
      'Grower' : 1,
      'Improver' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Hunting Party' : {
      'Cornucopia' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Selfmiller' : 1,
      'Speeder' : 3,
      'Variance' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Jester' : {
      'Cornucopia' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Coinage' : 2,
      'Attack' : 1,
      'Giver' : 1,
      'Miller' : 1,
      'Spier' : 1,
      'Variance' : 3,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Menagerie' : {
      'Cornucopia' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Speeder' : 2,
      'Variance' : 2,
      'Antiterminus' : 1
    },
    'Remake' : {
      'Cornucopia' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : -2,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Tournament' : {
      'Cornucopia' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Discardcasher' : 1,
      'Attack' : 0.5,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Improver' : 1,
      'Variance' : 4,
      'Chooser' : 1,
      'Interactive' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Young Witch' : {
      'Cornucopia' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Attack' : 1,
      'Giver' : 1,
      'Speeder' : 2,
      'Variance' : 2,
      'Chooser' : 1,
      'Interactive' : 2
    },
    'Crossroads' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Duchess' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 0.5,
      'Coinage' : 2,
      'Scouter' : 1,
      'Chooser' : 1,
      'Deckchanger' : 0.5
    },
    'Fool\'s Gold' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Treasure' : 1,
      'Reaction' : 1,
      'Multicolor' : 1,
      'Cumulative' : 2,
      'Mutator' : 1,
      'Helper' : 1,
      'Variance' : 4,
      'Interactive' : 2,
      'Antiterminus' : 1
    },
    'Develop' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Multiplier' : 1,
      'Cumulative' : 2,
      'Gainer' : 1,
      'Selftrasher' : 1,
      'Helper' : 1,
      'Topdecker' : 1,
      'Speeder' : -1,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 2,
      'Brancher' : 1
    },
    'Oasis' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Oracle' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Attack' : 1,
      'Scouter' : 2,
      'Selfmiller' : 2,
      'Miller' : 2,
      'Speeder' : 2,
      'Slower' : 2,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 2
    },
    'Scheme' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Tunnel' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Victory' : 2,
      'Reaction' : 1,
      'Multicolor' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Blocker' : 1,
      'Grower' : 1,
      'Variance' : 3,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Jack of all Trades' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost4' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Gainer' : 1,
      'Carddrawer' : 1,
      'Selftrasher' : 1,
      'Blocker' : 1,
      'Grower' : 1,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Deckchanger' : 2
    },
    'Noble Brigand' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Attack' : 1,
      'Miller' : 2,
      'Variance' : 3,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Nomad Camp' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Gainer' : 2,
      'Deckchanger' : 3
    },
    'Silk Road' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Victory' : 2,
      'Antisplitter' : 1,
      'Interactive' : 1
    },
    'Spice Merchant' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Coinage' : 2,
      'Carddrawer' : 1,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Trader' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Gainer' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 1
    },
    'Cache' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Cartographer' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Scouter' : 4,
      'Topdecker' : 2,
      'Speeder' : 5,
      'Chooser' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Embassy' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Speeder' : 5,
      'Variance' : 1,
      'Chooser' : 1
    },
    'Haggler' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 2,
      'Gainer' : 1,
      'Coinage' : 2,
      'Variance' : 2,
      'Chooser' : 2,
      'Deckchanger' : 1
    },
    'Highway' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 2,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Ill-Gotten Gains' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Antisplitter' : 1,
      'Gainer' : 1,
      'Attack' : 1,
      'Giver' : 1,
      'Chooser' : 2,
      'Interactive' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Inn' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Splitter' : 1,
      'Antisplitter' : 1,
      'Speeder' : 2,
      'Variance' : 1,
      'Chooser' : 1,
      'Brancher' : 1
    },
    'Mandarin' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 3,
      'Carddrawer' : -1,
      'Topdecker' : 1,
      'Speeder' : -1,
      'Variance' : 1,
      'Chooser' : 1
    },
    'Margrave' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Carddrawer' : 3,
      'Attack' : 1,
      'Shrinker' : 1,
      'Selfmiller' : 3,
      'Speeder' : 3,
      'Variance' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Stables' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Speeder' : 3,
      'Variance' : 1,
      'Chooser' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Border Village' : {
      'Hinterlands' : 1,
      'Hinterlands1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Gainer' : 0.5,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Deckchanger' : 0.5,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Farmland' : {
      'Hinterlands' : 1,
      'Hinterlands2' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Victory' : 4,
      'Multiplier' : 1,
      'Antisplitter' : 1,
      'Interactive' : 1,
      'Brancher' : 1
    },
    'Advisor' : {
      'Guilds' : 1,
      'Cost4' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 2,
      'Selfmiller' : 1,
      'Speeder' : 3,
      'Variance' : 1,
      'Antiterminus' : 1
    },
    'Baker' : {
      'Guilds' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Coinage' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Butcher' : {
      'Guilds' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 2,
      'Mutator' : 1,
      'Improver' : 1,
      'Variance' : 2,
      'Chooser' : 3,
      'Antiterminus' : 1
    },
    'Candlestick Maker' : {
      'Guilds' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Doctor' : {
      'Guilds' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Medium' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Selftrasher' : 1,
      'Scouter' : 2,
      'Selfmiller' : 2,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Deckchanger' : 1
    },
    'Masterpiece' : {
      'Guilds' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Antisplitter' : 1,
      'Gainer' : 1,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Journeyman' : {
      'Guilds' : 1,
      'Cost5' : 1,
      'Cheap' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Selfmiller' : 1,
      'Speeder' : 4,
      'Variance' : 2,
      'Chooser' : 2
    },
    'Plaza' : {
      'Guilds' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Merchant Guild' : {
      'Guilds' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 1,
      'Chooser' : 1,
      'Deckchanger' : 1
    },
    'Stonemason' : {
      'Guilds' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Gainer' : 1,
      'Selftrasher' : 1,
      'Variance' : 1,
      'Chooser' : 1,
      'Deckchanger' : 2
    },
    'Soothsayer' : {
      'Guilds' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Attack' : 1,
      'Giver' : 1,
      'Helper' : 1,
      'Interactive' : 3
    },
    'Herald' : {
      'Guilds' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Variance' : 3,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Taxman' : {
      'Guilds' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Mutator' : 1,
      'Attack' : 1,
      'Shrinker' : 1,
      'Miller' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Interactive' : 2,
      'Antiterminus' : 1
    },
    'Altar' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : -1,
      'Mutator' : 1,
      'Variance' : 2,
      'Chooser' : 2,
      'Antiterminus' : 1
    },
    'Armory' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Topdecker' : 1,
      'Speeder' : 2,
      'Chooser' : 2,
      'Deckchanger' : 1
    },
    'Band of Misfits' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Multiplier' : 1,
      'Cumulative' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Brancher' : 1
    },
    'Bandit Camp' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Gainer' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Deckchanger' : 1,
      'Brancher' : 1
    },
    'Beggar' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 2,
      'Coinage' : 3,
      'Carddrawer' : 3,
      'Blocker' : 1,
      'Topdecker' : 1,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 2
    },
    'Catacombs' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 3,
      'Selfmiller' : 2,
      'Speeder' : 3,
      'Variance' : 1,
      'Chooser' : 2
    },
    'Count' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Gainer' : 1,
      'Coinage' : 3,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Topdecker' : 1,
      'Speeder' : -1,
      'Variance' : 2,
      'Chooser' : 3,
      'Deckchanger' : 2
    },
    'Counterfeit' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Treasure' : 1,
      'Chainer' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Coinage' : 2,
      'Selftrasher' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Deckchanger' : 2,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Cultist' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Looter' : 1,
      'Terminus' : 1,
      'Cumulative' : 2,
      'Buyer' : 1,
      'Carddrawer' : 2,
      'Attack' : 1,
      'Giver' : 1,
      'Selfmiller' : 1,
      'Speeder' : 2,
      'Variance' : 3,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Death Cart' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Looter' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.7,
      'Antisplitter' : 0.3,
      'Gainer' : 1,
      'Coinage' : 5,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Variance' : 3,
      'Chooser' : 2,
      'Deckchanger' : 2
    },
    'Feodum' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Victory' : 2,
      'Antisplitter' : 1,
      'Variance' : 1,
      'Chooser' : 1,
      'Interactive' : 1
    },
    'Forager' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Buyer' : 1,
      'Coinage' : 2,
      'Carddrawer' : -1,
      'Selftrasher' : 1,
      'Helper' : 1,
      'Improver' : 1,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 2,
      'Antiterminus' : 1
    },
    'Fortress' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Splitter' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Brancher' : 1
    },
    'Graverobber' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Gainer' : 1,
      'Mutator' : 1,
      'Topdecker' : 1,
      'Variance' : 3,
      'Chooser' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Hermit' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Splitter' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Gainer' : 1,
      'Selftrasher' : 1,
      'Mutator' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 2,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Hunting Grounds' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost6' : 1,
      'Expensive' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 4,
      'Selfmiller' : 4,
      'Speeder' : 4,
      'Variance' : 1
    },
    'Ironmonger' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Coinage' : 1,
      'Discounter' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Junk Dealer' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Coinage' : 1,
      'Selftrasher' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 1,
      'Deckchanger' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Knights' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Attack' : 1,
      'Blocker' : 1,
      'Trasher' : 1,
      'Miller' : 2,
      'Variance' : 2,
      'Interactive' : 2
    },
    'Marauder' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Looter' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Attack' : 1,
      'Giver' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Market Square' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Reaction' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Buyer' : 1,
      'Gainer' : 1,
      'Carddrawer' : 1,
      'Speeder' : 1,
      'Variance' : 3,
      'Chooser' : 2,
      'Interactive' : 1,
      'Deckchanger' : 2,
      'Antiterminus' : 1
    },
    'Mystic' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Variance' : 2,
      'Chooser' : 3,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Pillage' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Mutator' : 1,
      'Attack' : 1,
      'Shrinker' : 1,
      'Variance' : 3,
      'Chooser' : 1,
      'Interactive' : 2,
      'Antiterminus' : 1
    },
    'Poor House' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Coinage' : 2,
      'Variance' : 2
    },
    'Procession' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Multiplier' : 1,
      'Cumulative' : 2,
      'Mutator' : 1,
      'Variance' : 3,
      'Chooser' : 3,
      'Brancher' : 1,
      'Antiterminus' : 1
    },
    'Rats' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Selftrasher' : 1,
      'Mutator' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Rebuild' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Mutator' : 1,
      'Selfmiller' : 3,
      'Speeder' : 3,
      'Improver' : 1,
      'Variance' : 1,
      'Chooser' : 1,
      'Medichainer' : 1,
      'Antiterminus' : 1
    },
    'Rogue' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost5' : 1,
      'Medium' : 1,
      'Terminus' : 1,
      'Cumulative' : 1,
      'Gainer' : 1,
      'Coinage' : 2,
      'Attack' : 1,
      'Trasher' : 1,
      'Miller' : 2,
      'Improver' : 1,
      'Variance' : 3,
      'Chooser' : 1,
      'Interactive' : 2,
      'Deckchanger' : 1
    },
    'Sage' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Variance' : 2,
      'Chooser' : 1,
      'Antiterminus' : 1
    },
    'Scavenger' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Coinage' : 2,
      'Topdecker' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 2
    },
    'Squire' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Buyer' : 2,
      'Gainer' : 1,
      'Coinage' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 3,
      'Brancher' : 1
    },
    'Storeroom' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Terminus' : 1,
      'Antisplitter' : 1,
      'Buyer' : 1,
      'Coinage' : 2,
      'Discardcasher' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 3,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Urchin' : {
      'DarkAges' : 1,
      'DarkAges3' : 1,
      'Cost3' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Terminus' : 1,
      'Cumulative' : 0.5,
      'Antisplitter' : 0.5,
      'Carddrawer' : 1,
      'Selftrasher' : 1,
      'Attack' : 1,
      'Shrinker' : 2,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Variance' : 1,
      'Chooser' : 2,
      'Interactive' : 2,
      'Deckchanger' : 1,
      'Antiterminus' : 1
    },
    'Vagrant' : {
      'DarkAges' : 1,
      'DarkAges1' : 1,
      'Cost2' : 1,
      'Cheap' : 1,
      'Chainer' : 1,
      'Cumulative' : 1,
      'Carddrawer' : 1,
      'Scouter' : 1,
      'Speeder' : 1,
      'Improver' : 1,
      'Antiterminus' : 1
    },
    'Wandering Minstrel' : {
      'DarkAges' : 1,
      'DarkAges2' : 1,
      'Cost4' : 1,
      'Cheap' : 1,
      'Splitter' : 1,
      'Cumulative' : 1,
      'Antisplitter' : 1,
      'Carddrawer' : 1,
      'Scouter' : 3,
      'Topdecker' : 1,
      'Selfmiller' : 1,
      'Speeder' : 1,
      'Improver' : 1,
      'Variance' : 2,
      'Brancher' : 1
    }  
  },
  cardNames: {
    'Alchemist': 1,
    'Apothecary': 1,
    'Apprentice': 1,
    'Familiar': 1,
    'Golem': 1,
    'Herbalist': 1,
    'Philosopher\'s Stone': 1,
    'Possession': 1,
    'Scrying Pool': 1,
    'Transmute': 1,
    'University': 1,
    'Vineyard': 1,
    'Black Market': 1,
    'Envoy': 1,
    'Stash': 1,
    'Walled Village': 1,
    'Governor': 1,
    'Adventurer': 1,
    'Bureaucrat': 1,
    'Cellar': 1,
    'Chancellor': 1,
    'Chapel': 1,
    'Council Room': 1,
    'Feast': 1,
    'Festival': 1,
    'Gardens': 1,
    'Laboratory': 1,
    'Library': 1,
    'Market': 1,
    'Militia': 1,
    'Mine': 1,
    'Moat': 1,
    'Moneylender': 1,
    'Remodel': 1,
    'Smithy': 1,
    'Spy': 1,
    'Thief': 1,
    'Throne Room': 1,
    'Village': 1,
    'Witch': 1,
    'Woodcutter': 1,
    'Workshop': 1,
    'Baron': 1,
    'Bridge': 1,
    'Conspirator': 1,
    'Coppersmith': 1,
    'Courtyard': 1,
    'Duke': 1,
    'Great Hall': 1,
    'Harem': 1,
    'Ironworks': 1,
    'Masquerade': 1,
    'Mining Village': 1,
    'Minion': 1,
    'Nobles': 1,
    'Pawn': 1,
    'Saboteur': 1,
    'Scout': 1,
    'Secret Chamber': 1,
    'Shanty Town': 1,
    'Steward': 1,
    'Swindler': 1,
    'Torturer': 1,
    'Trading Post': 1,
    'Tribute': 1,
    'Upgrade': 1,
    'Wishing Well': 1,
    'Bank': 1,
    'Bishop': 1,
    'City': 1,
    'Contraband': 1,
    'Counting House': 1,
    'Expand': 1,
    'Forge': 1,
    'Goons': 1,
    'Grand Market': 1,
    'Hoard': 1,
    'King\'s Court': 1,
    'Loan': 1,
    'Mint': 1,
    'Monument': 1,
    'Mountebank': 1,
    'Peddler': 1,
    'Quarry': 1,
    'Rabble': 1,
    'Royal Seal': 1,
    'Talisman': 1,
    'Trade Route': 1,
    'Vault': 1,
    'Venture': 1,
    'Watchtower': 1,
    'Worker\'s Village': 1,
    'Ambassador': 1,
    'Bazaar': 1,
    'Caravan': 1,
    'Cutpurse': 1,
    'Embargo': 1,
    'Explorer': 1,
    'Fishing Village': 1,
    'Ghost Ship': 1,
    'Haven': 1,
    'Island': 1,
    'Lighthouse': 1,
    'Lookout': 1,
    'Merchant Ship': 1,
    'Native Village': 1,
    'Navigator': 1,
    'Outpost': 1,
    'Pearl Diver': 1,
    'Pirate Ship': 1,
    'Salvager': 1,
    'Sea Hag': 1,
    'Smugglers': 1,
    'Tactician': 1,
    'Treasure Map': 1,
    'Treasury': 1,
    'Warehouse': 1,
    'Wharf': 1,
    'Fairgrounds': 1,
    'Farming Village': 1,
    'Fortune Teller': 1,
    'Hamlet': 1,
    'Harvest': 1,
    'Horn of Plenty': 1,
    'Horse Traders': 1,
    'Hunting Party': 1,
    'Jester': 1,
    'Menagerie': 1,
    'Remake': 1,
    'Tournament': 1,
    'Young Witch': 1,
    'Crossroads': 1,
    'Duchess': 1,
    'Fool\'s Gold': 1,
    'Develop': 1,
    'Oasis': 1,
    'Oracle': 1,
    'Scheme': 1,
    'Tunnel': 1,
    'Jack of all Trades': 1,
    'Noble Brigand': 1,
    'Nomad Camp': 1,
    'Silk Road': 1,
    'Spice Merchant': 1,
    'Trader': 1,
    'Cache': 1,
    'Cartographer': 1,
    'Embassy': 1,
    'Haggler': 1,
    'Highway': 1,
    'Ill-Gotten Gains': 1,
    'Inn': 1,
    'Mandarin': 1,
    'Margrave': 1,
    'Stables': 1,
    'Border Village': 1,
    'Farmland': 1,
    'Advisor': 1,
    'Baker': 1,
    'Butcher': 1,
    'Candlestick Maker': 1,
    'Doctor': 1,
    'Masterpiece': 1,
    'Journeyman': 1,
    'Plaza': 1,
    'Merchant Guild': 1,
    'Stonemason': 1,
    'Soothsayer': 1,
    'Herald': 1,
    'Taxman': 1,
    'Altar': 1,
    'Armory': 1,
    'Band of Misfits': 1,
    'Bandit Camp': 1,
    'Beggar': 1,
    'Catacombs': 1,
    'Count': 1,
    'Counterfeit': 1,
    'Cultist': 1,
    'Death Cart': 1,
    'Feodum': 1,
    'Forager': 1,
    'Fortress': 1,
    'Graverobber': 1,
    'Hermit': 1,
    'Hunting Grounds': 1,
    'Ironmonger': 1,
    'Junk Dealer': 1,
    'Knights': 1,
    'Marauder': 1,
    'Market Square': 1,
    'Mystic': 1,
    'Pillage': 1,
    'Poor House': 1,
    'Procession': 1,
    'Rats': 1,
    'Rebuild': 1,
    'Rogue': 1,
    'Sage': 1,
    'Scavenger': 1,
    'Squire': 1,
    'Storeroom': 1,
    'Urchin': 1,
    'Vagrant': 1,
    'Wandering Minstrel': 1
  },
  cardAttributes: {
    'Base': 1,
    'Intrigue': 1,
    'Seaside': 1,
    'Alchemy': 1,
    'Prosperity': 1,
    'Cornucopia': 1,
    'Hinterlands': 1,
    'Guilds': 1,
    'DarkAges': 1,
    'Promo': 1,
    'Stash': 1,
    'WalledVillage': 1,
    'Governor': 1,
    'Envoy': 1,
    'BlackMarket': 1,
    'Intrigue1': 1,
    'Intrigue2': 1,
    'Seaside1': 1,
    'Seaside2': 1,
    'Prosperity1': 1,
    'Prosperity2': 1,
    'Hinterlands1': 1,
    'Hinterlands2': 1,
    'DarkAges1': 1,
    'DarkAges2': 1,
    'DarkAges3': 1,
    'Cost2': 1,
    'Cost3': 1,
    'Cost4': 1,
    'Cost5': 1,
    'Cost6': 1,
    'Cost7': 1,
    'Cheap': 1,
    'Medium': 1,
    'Expensive': 1,
    'Victory': 1,
    'Chipper': 1,
    'Treasure': 1,
    'Duration': 1,
    'Looter': 1,
    'Reaction': 1,
    'Multicolor': 1,
    'Chainer': 1,
    'Splitter': 1,
    'Terminus': 1,
    'Multiplier': 1,
    'Duration': 1,
    'Cumulative': 1,
    'Antisplitter': 1,
    'Buyer': 1,
    'Gainer': 1,
    'Coinage': 1,
    'Discounter': 1,
    'Carddrawer': 1,
    'Selftrasher': 1,
    'Mutator': 1,
    'Discardcasher': 1,
    'Attack': 1,
    'Blocker': 1,
    'Giver': 1,
    'Trasher': 1,
    'Helper': 1,
    'Shrinker': 1,
    'Grower': 1,
    'Scouter': 1,
    'Topdecker': 1,
    'Selfmiller': 1,
    'Miller': 1,
    'Spier': 1,
    'Speeder': 1,
    'Slower': 1,
    'Improver': 1,
    'Variance': 1,
    'Chooser': 1,
    'Interactive': 1,
    'Deckchanger': 1,
    'Medichainer': 1,
    'Brancher': 1,
    'Antiterminus': 1
  },
  Min: {
    'Base' : 0,
    'Intrigue' : 0,
    'Seaside' : 0,
    'Alchemy' : 0,
    'Prosperity' : 0,
    'Cornucopia' : 0,
    'Hinterlands' : 0,
    'Guilds' : 0,
    'DarkAges' : 0,
    'Promo' : 0,
    'Stash' : 0,
    'WalledVillage' : 0,
    'Governor' : 0,
    'Envoy' : 0,
    'BlackMarket' : 0,
    'Intrigue1' : 0,
    'Intrigue2' : 0,
    'Seaside1' : 0,
    'Seaside2' : 0,
    'Prosperity1' : 0,
    'Prosperity2' : 0,
    'Hinterlands1' : 0,
    'Hinterlands2' : 0,
    'DarkAges1' : 0,
    'DarkAges2' : 0,
    'DarkAges3' : 0,
    'Cost2' : 0,
    'Cost3' : 0,
    'Cost4' : 0,
    'Cost5' : 0,
    'Cost6' : 0,
    'Cost7' : 0,
    'Cheap' : 2,
    'Medium' : 2,
    'Expensive' : 0,
    'Victory' : 0,
    'Chipper' : 0,
    'Treasure' : 0,
    'Duration' : 0,
    'Looter' : 0,
    'Reaction' : 0,
    'Multicolor' : 0,
    'Chainer' : 0,
    'Splitter' : 0,
    'Terminus' : 0,
    'Multiplier' : 0,
    'Duration' : 0,
    'Cumulative' : 0,
    'Antisplitter' : 0,
    'Buyer' : 0,
    'Gainer' : 0,
    'Coinage' : 1,
    'Discounter' : 0,
    'Carddrawer' : 8,
    'Selftrasher' : 0,
    'Mutator' : 1,
    'Discardcasher' : 0,
    'Attack' : 0,
    'Blocker' : 0,
    'Giver' : 0,
    'Trasher' : 0,
    'Helper' : 0,
    'Shrinker' : 0,
    'Grower' : 0,
    'Scouter' : 0,
    'Topdecker' : 0,
    'Selfmiller' : 0,
    'Miller' : 0,
    'Spier' : 0,
    'Speeder' : 5,
    'Slower' : 0,
    'Improver' : 0,
    'Variance' : 0,
    'Chooser' : 5,
    'Interactive' : 3,
    'Deckchanger' : 2,
    'Medichainer' : 1,
    'Brancher' : 1,
    'Antiterminus' : 3
  },
  Max: {
    'Base' : 0,
    'Intrigue' : 0,
    'Seaside' : 0,
    'Alchemy' : 0,
    'Prosperity' : 0,
    'Cornucopia' : 0,
    'Hinterlands' : 0,
    'Guilds' : 0,
    'DarkAges' : 0,
    'Promo' : 0,
    'Stash' : 0,
    'WalledVillage' : 0,
    'Governor' : 0,
    'Envoy' : 0,
    'BlackMarket' : 0,
    'Intrigue1' : 0,
    'Intrigue2' : 0,
    'Seaside1' : 0,
    'Seaside2' : 0,
    'Prosperity1' : 0,
    'Prosperity2' : 0,
    'Hinterlands1' : 0,
    'Hinterlands2' : 0,
    'DarkAges1' : 0,
    'DarkAges2' : 0,
    'DarkAges3' : 0,
    'Cost2' : 0,
    'Cost3' : 0,
    'Cost4' : 0,
    'Cost5' : 0,
    'Cost6' : 0,
    'Cost7' : 0,
    'Cheap' : 7,
    'Medium' : 0,
    'Expensive' : 0,
    'Victory' : 0,
    'Chipper' : 0,
    'Treasure' : 0,
    'Duration' : 0,
    'Looter' : 0,
    'Reaction' : 0,
    'Multicolor' : 0,
    'Chainer' : 0,
    'Splitter' : 0,
    'Terminus' : 6,
    'Multiplier' : 0,
    'Duration' : 0,
    'Cumulative' : 0,
    'Antisplitter' : 7,
    'Buyer' : 0,
    'Gainer' : 0,
    'Coinage' : 0,
    'Discounter' : 0,
    'Carddrawer' : 8,
    'Selftrasher' : 0,
    'Mutator' : 0,
    'Discardcasher' : 0,
    'Attack' : 0,
    'Blocker' : 0,
    'Giver' : 2,
    'Trasher' : 0,
    'Helper' : 0,
    'Shrinker' : 2,
    'Grower' : 0,
    'Scouter' : 0,
    'Topdecker' : 0,
    'Selfmiller' : 0,
    'Miller' : 0,
    'Spier' : 0,
    'Speeder' : 12,
    'Slower' : 0,
    'Improver' : 0,
    'Variance' : 15,
    'Chooser' : 0,
    'Interactive' : 6,
    'Deckchanger' : 0,
    'Medichainer' : 0,
    'Brancher' : 3,
    'Antiterminus' : 0
  },
  MinW: {
    'Base' : 1,
    'Intrigue' : 1,
    'Seaside' : 1,
    'Alchemy' : 1,
    'Prosperity' : 1,
    'Cornucopia' : 1,
    'Hinterlands' : 1,
    'Guilds' : 1,
    'DarkAges' : 1,
    'Promo' : 1,
    'Stash' : 1,
    'WalledVillage' : 1,
    'Governor' : 1,
    'Envoy' : 1,
    'BlackMarket' : 1,
    'Intrigue1' : 1,
    'Intrigue2' : 1,
    'Seaside1' : 1,
    'Seaside2' : 1,
    'Prosperity1' : 1,
    'Prosperity2' : 1,
    'Hinterlands1' : 1,
    'Hinterlands2' : 1,
    'DarkAges1' : 1,
    'DarkAges2' : 1,
    'DarkAges3' : 1,
    'Cost2' : 1,
    'Cost3' : 1,
    'Cost4' : 1,
    'Cost5' : 1,
    'Cost6' : 1,
    'Cost7' : 1,
    'Cheap' : 1.25,
    'Medium' : 4,
    'Expensive' : 1,
    'Victory' : 1,
    'Chipper' : 1,
    'Treasure' : 1,
    'Duration' : 1,
    'Looter' : 1,
    'Reaction' : 1,
    'Multicolor' : 1,
    'Chainer' : 1,
    'Splitter' : 1,
    'Terminus' : 1.25,
    'Multiplier' : 1,
    'Duration' : 1,
    'Cumulative' : 1,
    'Antisplitter' : 1,
    'Buyer' : 1,
    'Gainer' : 1,
    'Coinage' : 1.1,
    'Discounter' : 1,
    'Carddrawer' : 3,
    'Selftrasher' : 1,
    'Mutator' : 1.25,
    'Discardcasher' : 1,
    'Attack' : 1,
    'Blocker' : 1,
    'Giver' : 1,
    'Trasher' : 1,
    'Helper' : 1,
    'Shrinker' : 1,
    'Grower' : 1,
    'Scouter' : 1,
    'Topdecker' : 1,
    'Selfmiller' : 1,
    'Miller' : 1,
    'Spier' : 1,
    'Speeder' : 1.5,
    'Slower' : 1,
    'Improver' : 1,
    'Variance' : 1,
    'Chooser' : 1.5,
    'Interactive' : 1.25,
    'Deckchanger' : 4,
    'Medichainer' : 4,
    'Brancher' : 1.25,
    'Antiterminus' : 1.5
  },
  MaxW: {
    'Base' : 1.1,
    'Intrigue' : 1.1,
    'Seaside' : 1.1,
    'Alchemy' : 3.5,
    'Prosperity' : 1.25,
    'Cornucopia' : 2.5,
    'Hinterlands' : 1.1,
    'Guilds' : 2.5,
    'DarkAges' : 1.1,
    'Promo' : 1,
    'Stash' : 1,
    'WalledVillage' : 1,
    'Governor' : 1,
    'Envoy' : 1,
    'BlackMarket' : 1,
    'Intrigue1' : 1,
    'Intrigue2' : 1,
    'Seaside1' : 1,
    'Seaside2' : 1,
    'Prosperity1' : 1,
    'Prosperity2' : 1,
    'Hinterlands1' : 1,
    'Hinterlands2' : 1,
    'DarkAges1' : 1,
    'DarkAges2' : 1,
    'DarkAges3' : 1,
    'Cost2' : 1,
    'Cost3' : 1,
    'Cost4' : 1,
    'Cost5' : 1,
    'Cost6' : 1,
    'Cost7' : 1,
    'Cheap' : 0.8,
    'Medium' : 1,
    'Expensive' : 1.25,
    'Victory' : 1,
    'Chipper' : 1,
    'Treasure' : 1,
    'Duration' : 1,
    'Looter' : 1,
    'Reaction' : 1,
    'Multicolor' : 1,
    'Chainer' : 1,
    'Splitter' : 1,
    'Terminus' : 0.8,
    'Multiplier' : 1,
    'Duration' : 1,
    'Cumulative' : 1,
    'Antisplitter' : 0.25,
    'Buyer' : 1,
    'Gainer' : 1,
    'Coinage' : 1,
    'Discounter' : 1,
    'Carddrawer' : 0.95,
    'Selftrasher' : 1,
    'Mutator' : 1,
    'Discardcasher' : 1,
    'Attack' : 1,
    'Blocker' : 1.25,
    'Giver' : 0.5,
    'Trasher' : 1,
    'Helper' : 0.8,
    'Shrinker' : 0.5,
    'Grower' : 0.8,
    'Scouter' : 0.5,
    'Topdecker' : 0.8,
    'Selfmiller' : 0.95,
    'Miller' : 0.5,
    'Spier' : 0.5,
    'Speeder' : 0.95,
    'Slower' : 0.2,
    'Improver' : 0.8,
    'Variance' : 0.98,
    'Chooser' : 1,
    'Interactive' : 0.8,
    'Deckchanger' : 1,
    'Medichainer' : 1,
    'Brancher' : 0.95,
    'Antiterminus' : 1
  },
  UserMax: {
    'Base' : 10,
    'Intrigue' : 10,
    'Seaside' : 10,
    'Alchemy' : 10,
    'Prosperity' : 10,
    'Cornucopia' : 10,
    'Hinterlands' : 10,
    'Guilds' : 10,
    'DarkAges' : 10,
    'Promo' : 10,
    'Stash' : 10,
    'WalledVillage' : 10,
    'Governor' : 10,
    'Envoy' : 10,
    'BlackMarket' : 10,
    'Intrigue1' : 10,
    'Intrigue2' : 10,
    'Seaside1' : 10,
    'Seaside2' : 10,
    'Prosperity1' : 10,
    'Prosperity2' : 10,
    'Hinterlands1' : 10,
    'Hinterlands2' : 10,
    'DarkAges1' : 10,
    'DarkAges2' : 10,
    'DarkAges3' : 10,
    'Cost2' : 10,
    'Cost3' : 10,
    'Cost4' : 10,
    'Cost5' : 10,
    'Cost6' : 10,
    'Cost7' : 10,
    'Cheap' : 10,
    'Medium' : 10,
    'Expensive' : 10,
    'Victory' : 10,
    'Chipper' : 10,
    'Treasure' : 10,
    'Duration' : 10,
    'Looter' : 10,
    'Reaction' : 10,
    'Multicolor' : 10,
    'Chainer' : 10,
    'Splitter' : 10,
    'Terminus' : 10,
    'Multiplier' : 10,
    'Duration' : 10,
    'Cumulative' : 10,
    'Antisplitter' : 10,
    'Buyer' : 10,
    'Gainer' : 10,
    'Coinage' : 10,
    'Discounter' : 10,
    'Carddrawer' : 10,
    'Selftrasher' : 10,
    'Mutator' : 10,
    'Discardcasher' : 10,
    'Attack' : 10,
    'Blocker' : 10,
    'Giver' : 10,
    'Trasher' : 10,
    'Helper' : 10,
    'Shrinker' : 10,
    'Grower' : 10,
    'Scouter' : 10,
    'Topdecker' : 10,
    'Selfmiller' : 10,
    'Miller' : 10,
    'Spier' : 10,
    'Speeder' : 10,
    'Slower' : 10,
    'Improver' : 10,
    'Variance' : 10,
    'Chooser' : 10,
    'Interactive' : 10,
    'Deckchanger' : 10,
    'Medichainer' : 10,
    'Brancher' : 10,
    'Antiterminus' : 10
  },
  Notes: {
    'Base' : 'Somewhat Dense',
    'Intrigue' : 'Somewhat Dense',
    'Seaside' : 'Somewhat Dense',
    'Alchemy' : 'Very Strongly Dense',
    'Prosperity' : 'Dense',
    'Cornucopia' : 'Strongly Dense',
    'Hinterlands' : 'Somewhat Dense',
    'Guilds' : 'Strongly Dense',
    'DarkAges' : 'Somewhat Dense',
    'Promo' : '',
    'Stash' : '',
    'WalledVillage' : '',
    'Governor' : '',
    'Envoy' : '',
    'BlackMarket' : '',
    'Intrigue1' : '',
    'Intrigue2' : '',
    'Seaside1' : '',
    'Seaside2' : '',
    'Prosperity1' : '',
    'Prosperity2' : '',
    'Hinterlands1' : '',
    'Hinterlands2' : '',
    'DarkAges1' : '',
    'DarkAges2' : '',
    'DarkAges3' : '',
    'Cost2' : '',
    'Cost3' : '',
    'Cost4' : '',
    'Cost5' : '',
    'Cost6' : '',
    'Cost7' : '',
    'Cheap' : 'Range 2-6',
    'Medium' : 'Strongly at least 2',
    'Expensive' : 'Dense',
    'Victory' : '',
    'Chipper' : '',
    'Treasure' : 'See Antiterminus',
    'Duration' : '',
    'Looter' : '',
    'Reaction' : '',
    'Multicolor' : '',
    'Chainer' : 'See Antiterminus',
    'Splitter' : 'See Brancher',
    'Terminus' : '0-6 Range',
    'Multiplier' : 'See Brancher',
    'Duration' : '',
    'Cumulative' : 'See Antisplitter',
    'Antisplitter' : 'No more than 7',
    'Buyer' : 'See Deckchanger',
    'Gainer' : 'See Deckchanger',
    'Coinage' : 'Really Weakly at least 1',
    'Discounter' : '',
    'Carddrawer' : 'Weakly Sparse, at least 8',
    'Selftrasher' : 'See Deckchanger',
    'Mutator' : 'Weakly at least 1',
    'Discardcasher' : 'See Antiterminus',
    'Attack' : 'See Interactive',
    'Blocker' : 'Mildly Dense',
    'Giver' : 'At most 2',
    'Trasher' : 'See Deckchanger',
    'Helper' : 'Sparse',
    'Shrinker' : 'At most 2',
    'Grower' : 'Sparse',
    'Scouter' : 'Strongly Sparse',
    'Topdecker' : 'Sparse',
    'Selfmiller' : 'Weakly Sparse',
    'Miller' : 'Strongly Sparse',
    'Spier' : 'Strongly Sparse',
    'Speeder' : '5-12 Range',
    'Slower' : 'Strongly Sparse',
    'Improver' : 'Sparse',
    'Variance' : 'At most 15',
    'Chooser' : 'Weakly at least 5',
    'Interactive' : '3-6 Range',
    'Deckchanger' : 'Strongly at least 2',
    'Medichainer' : 'Strongly at least 1',
    'Brancher' : 'At least 1, weakly <= 3',
    'Antiterminus' : 'Weakly at least 3'
  }
};
